### ISSUE TITLE
Basic Auth not work

### ISSUE THREAD

**Issue by ElvizLai** [codeskyblue/gohttp#3]
not worked if : `./file-server -port 8080 -root data/ -private true -auth abc:123123`

but works: `./file-server -port 8080 -root data/ -auth abc:123123 -private true`

I think the Auth should not block `Get` method.

**Comment by codeskyblue** [comment]
It will work if you use

    ./file-server -port 8080 -root data/ -private=true -auth abc:123123

The difference is `-private=true` vs `-private true`
