### ISSUE TITLE
can not see any file in browser when server running

### ISSUE THREAD

**Issue by qihigh** [codeskyblue/gohttp#5]
I got the server gohttp from Binary release download . When I setup the server by ``` ./gohttp --port 8000 --root /Users/qihuan/ ``` . A page show on address ``` http://127.0.0.1:8000/ ``` in browser . But no file list. These is not error list in go console,but ``` Uncaught Error: Cannot find module "highlight.js" ``` shown in browser in chrome's console.

**Comment by codeskyblue** [comment]
I see that too, I'm tring to find out why?

**Comment by codeskyblue** [comment]
@qihigh Should fix now. I added highlight to package.json

**Comment by qihigh** [comment]
it works!

**Comment by qihigh** [comment]
very convenient tools, good job!
