### ISSUE TITLE
fail to get all static files (500) like js/css

### ISSUE THREAD

**Issue by ynsfsmj** [codeskyblue/gohttp#8]
[markwhat@markwhat runspace]$ ./gohttp 
2016/04/21 20:22:08 listens on 0.0.0.0@8000
[Macaron] Started GET / for 166.111.132.27
[Macaron] Completed / 200 OK in 1.000795ms
[Macaron] Started GET /-/css/bootstrap.min.css for 166.111.132.27
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/panic.go:423 (0x807187d)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/panic.go:42 (0x8070353)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/sigpanic_unix.go:24 (0x8084144)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 (0x8363cd1)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/static.go:134 (0x8124d16)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/static.go:184 (0x812b7e6)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/asm_386.s:442 (0x809857a)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:432 (0x8230908)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:300 (0x822f92c)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/github.com/go-macaron/inject/inject.go:117 (0x82aac44)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/context.go:113 (0x8118d24)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/context.go:104 (0x8118c38)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/recovery.go:161 (0x8129f2b)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/asm_386.s:442 (0x809857a)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:432 (0x8230908)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:300 (0x822f92c)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/github.com/go-macaron/inject/inject.go:117 (0x82aac44)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/context.go:113 (0x8118d24)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/context.go:104 (0x8118c38)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/logger.go:40 (0x8128eee)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/asm_386.s:442 (0x809857a)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:432 (0x8230908)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/reflect/value.go:300 (0x822f92c)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/github.com/go-macaron/inject/inject.go:117 (0x82aac44)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/context.go:113 (0x8118d24)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/router.go:184 (0x812b202)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/router.go:286 (0x8123a8d)
/home/travis/gopath/src/github.com/codeskyblue/gohttp/Godeps/_workspace/src/gopkg.in/macaron.v1/macaron.go:175 (0x811d19f)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/server.go:1699 (0x80b8223)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/server.go:1862 (0x80b8a76)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/server.go:1361 (0x80b6935)
/home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/asm_386.s:1662 (0x809a491)
[Macaron] Completed /-/css/bootstrap.min.css 500 Internal Server Error in 2.162054ms

**Comment by ynsfsmj** [comment]
Thanks if you can tell me how to fix it! This project is nice:)

**Comment by codeskyblue** [comment]
it is hard for me to tell where goes wrong. You can try to build youself.   I will check that tomorrow

**Comment by codeskyblue** [comment]
@ynsfsmj Something went wrong with gobuild.io, build from source is ok.
